function genTest_DataType()
testStr = 'T10';
default=struct('numF',200,'preload',20,'depth',10,'fold',10,'Ftype','F_CHAR','numS',10*1e6,'numT',50,'numGPU',1,'weightType','W_ONES','baseDir','','prefix','','log','LOG2','comment','');

%Speed:
%T10: Need to test types: short, flow (4 types , machines=odem,k80 i.e. high precision versus low precision machines) = (8 Tests)
baseTestDir='100-100-7-';
testTypes={'CHAR','SHORT','FLOAT'};
machines= { ...
    'k5000m',  '/media/gipadmin/data/' ,  ...
    'k80',     '/home/aaron/forks/tea/data/'    ,  ...
    'titanz',  '/home/gipuser/forks/tea/data/'  ,  ...
    'gtx1080', '/home/aaron/forks/tea/data/'    ,  ...
    'gtx580',  '/home/admin/forks/tea/data/'    ,  ...
    };
T=default;
%% Constant test component
% --------------------------------
T.numF=100;
T.depth=16;
T.fold=16;
T.numS=100*1e6;
T.numT=10;
T.comment='Test: Timing different data types';
% --------------------------------
for i = 2:2:length(machines)
    machine = machines{i-1};
    T.prefix=['-' machine '-' testStr];
    f=fopen(sprintf('%s-%s.test',machine,testStr),'w');
    fprintf('%s\n',T.comment);
    fprintf('Machine: %s\n',machine);
    for d = testTypes
        %% Dynamic test component
        % --------------------------------
        baseDir = [machines{i} baseTestDir d{1}]  ;
        T.baseDir=baseDir;
        T.Ftype=['F_' d{1}];
        fprintf('%s\n',genTestString(T));
        fprintf(f,'%s\n',genTestString(T));
        % --------------------------------
    end
    fclose(f);
    fprintf('\n');
end


function testPrefix = genTestPrefix(T)
testPrefix = sprintf('%u-%u-%u-%u-%s-%u-%u-%u-%s', ...
    T.numF, ...
    T.preload, ...
    T.depth, ...
    T.fold, ...
    T.Ftype, ...
    T.numS, ...
    T.numT, ...
    T.numGPU, ...
    T.weightType);


function testStr = genTestString(T,dropCache)
dc='';
if exist('dropCache') && dropCache
    dc='sudo DROP_CACHE=1 ';
end

testStr = sprintf('%s./Tea %u %u %u %u %s %u %u 0 %u %s %s/ %s 0 %s "%s"', ...
    dc, ...
    T.numF, ...
    T.preload, ...
    T.depth, ...
    T.fold, ...
    T.Ftype, ...
    T.numS, ...
    T.numT, ...
    T.numGPU - 1, ...
    T.weightType, ...
    T.baseDir, ...
    [genTestPrefix(T) T.prefix], ...
    T.log, ...
    T.comment);

