function genTest_GPUs()

testStr = 'T7';

default=struct('numF',200,'preload',20,'depth',10,'fold',10,'Ftype','F_CHAR','numS',10*1e6,'numT',50,'numGPU',1,'weightType','W_ONES','baseDir','','prefix','','log','LOG2','comment','');

%Speed:
%T7: Need to test number of GPUs:1-4    (k80=0,1 + odem=0,1,2,3 + titan=0,1 + quadro=0 + he=0,1,2)=12 X (#samples=1m,10m,100m,1000m #features = 100)=4 -> (48 Tests)
testDir='200-100-7-char';
machines= { ...
    'k5000m',  ['/media/gipadmin/data/' testDir],  ...
    'k80',     ['/home/aaron/forks/tea/data/'    testDir],  ...
    'titanz',  ['/home/gipuser/forks/tea/data/'  testDir],  ...
    'gtx1080', ['/home/aaron/forks/tea/data/'    testDir],  ...
    'gtx580',  ['/home/admin/forks/tea/data/'    testDir],  ...
    };

gpus = containers.Map;
gpus('k5000m')=[1];
gpus('k80')=[1 2];
gpus('titanz')=[1 2];
gpus('gtx1080')=[1 2 3];
gpus('gtx580')=[1 2 3 4];

T=default;
%% Constant test component
% --------------------------------
T.numF=200;
T.depth=20;
T.fold =20;
T.numS=100*1e6;
T.numT=10;
T.comment='Test: Timing different number of GPUS';
% --------------------------------
for i = 2:2:length(machines)
    machine = machines{i-1};
    baseDir = machines{i};
    T.baseDir=baseDir;
    T.prefix=['-' machine '-' testStr];
    f=fopen(sprintf('%s-%s.test',machine,testStr),'w');
    fprintf('%s\n',T.comment);
    fprintf('Machine: %s\n',machine);
    for numGPU = gpus(machine)
        T.numGPU=numGPU;
        fprintf('%s\n',genTestString(T));
        fprintf(f,'%s\n',genTestString(T));
    end
    fprintf('\n');
    fclose(f);
end


function testPrefix = genTestPrefix(T)
testPrefix = sprintf('%u-%u-%u-%u-%s-%u-%u-%u-%s', ...
    T.numF, ...
    T.preload, ...
    T.depth, ...
    T.fold, ...
    T.Ftype, ...
    T.numS, ...
    T.numT, ...
    T.numGPU, ...
    T.weightType);


function testStr = genTestString(T,dropCache)
dc='';
if exist('dropCache') && dropCache
    dc='sudo DROP_CACHE=1 ';
end

testStr = sprintf('%s./Tea %u %u %u %u %s %u %u 0 %u %s %s/ %s 0 %s "%s"', ...
    dc, ...
    T.numF, ...
    T.preload, ...
    T.depth, ...
    T.fold, ...
    T.Ftype, ...
    T.numS, ...
    T.numT, ...
    T.numGPU - 1, ...
    T.weightType, ...
    T.baseDir, ...
    [genTestPrefix(T) T.prefix], ...
    T.log, ...
    T.comment);



