function genTest_Threshold()
testStr = 'T3';

default=struct('numF',200,'preload',20,'depth',10,'fold',10,'Ftype','F_CHAR','numS',10*1e6,'numT',50,'numGPU',1,'weightType','W_ONES','baseDir','','prefix','','log','LOG2','comment','');

%Speed:
%T3: Need to test number of thresholds:  Thresholds: 10 - 100 (10 Vals, 5 machines) = (50 Tests)
testDir='200-100-7-char';
machines= { ...
    'k5000m',  ['/media/gipadmin/data/' testDir],  ...
    'k80',     ['/home/aaron/forks/tea/data/'    testDir],  ...
    'titanz',  ['/home/gipuser/forks/tea/data/'  testDir],  ...
    'gtx1080', ['/home/aaron/forks/tea/data/'    testDir],  ...
    'gtx580',  ['/home/admin/forks/tea/data/'    testDir],  ...
    };
thresholds=[1 2 3 5 10 20 50 100 200];
T=default;
%% Constant test component
% --------------------------------
T.depth=14;
T.fold=14;
T.numS=100*1e6;
T.comment='Test: Timing different number of thresholds';
% --------------------------------
for i = 2:2:length(machines)
    machine = machines{i-1};
    baseDir = machines{i};
    T.prefix=['-' machine '-' testStr];
    T.baseDir=baseDir;
    f=fopen(sprintf('%s-%s.test',machine,testStr),'w');
    fprintf('%s\n',T.comment);
    fprintf('Machine: %s\n',machine);
    for threshold = thresholds
        %% Dynamic test component
        % --------------------------------
        T.numT=threshold;
        fprintf('%s\n',genTestString(T));
        fprintf(f,'%s\n',genTestString(T));
        % --------------------------------        
    end
    fclose(f);
    fprintf('\n');
end


function testPrefix = genTestPrefix(T)
testPrefix = sprintf('%u-%u-%u-%u-%s-%u-%u-%u-%s', ...
    T.numF, ...
    T.preload, ...
    T.depth, ...
    T.fold, ...
    T.Ftype, ...
    T.numS, ...
    T.numT, ...
    T.numGPU, ...
    T.weightType);


function testStr = genTestString(T,dropCache)
dc='';
if exist('dropCache') && dropCache
    dc='sudo DROP_CACHE=1 ';
end

testStr = sprintf('%s./Tea %u %u %u %u %s %u %u 0 %u %s %s/ %s 0 %s "%s"', ...
    dc, ...
    T.numF, ...
    T.preload, ...
    T.depth, ...
    T.fold, ...
    T.Ftype, ...
    T.numS, ...
    T.numT, ...
    T.numGPU - 1, ...
    T.weightType, ...
    T.baseDir, ...
    [genTestPrefix(T) T.prefix], ...
    T.log, ...
    T.comment);
