function genTest_Folding()
testStr = 'T5';
default=struct('numF',200,'preload',20,'depth',10,'fold',10,'Ftype','F_CHAR','numS',10*1e6,'numT',50,'numGPU',1,'weightType','W_ONES','baseDir','','prefix','','log','LOG2','comment','');

%Speed:
%T5: Need to test folding depth:  Folding depth 
% Can show a tree which "forks" after folding depth and is computed
% serially i.e. exponentially increasing computation time after folding
% depth?? (is this even true?)
testDir='20-100-7-char';
machines= { ...
    'k5000m',  ['/media/gipadmin/data/' testDir],  ...
    'k80',     ['/home/aaron/forks/tea/data/'    testDir],  ...
    'titanz',  ['/home/gipuser/forks/tea/data/'  testDir],  ...
    'gtx1080', ['/home/aaron/forks/tea/data/'    testDir],  ...
    'gtx580',  ['/home/admin/forks/tea/data/'    testDir],  ...
    };
folds=[14 16 18 20 22];
T=default;
%% Constant test component
% --------------------------------
T.numF=20;
T.depth=22;
T.numS=100*1e6;
T.numT=10;
T.comment='Test: Timing different folding depths';
% --------------------------------
for i = 2:2:length(machines)
    machine = machines{i-1};
    baseDir = machines{i};
    T.prefix=['-' machine '-' testStr];
    T.baseDir=baseDir;
    f=fopen(sprintf('%s-%s.test',machine,testStr),'w');
    fprintf('%s\n',T.comment);
    fprintf('Machine: %s\n',machine);
    for fold = folds
        %% Dynamic test component
        % --------------------------------
        T.fold=fold;
        fprintf('%s\n',genTestString(T));
        fprintf(f,'%s\n',genTestString(T));
        % --------------------------------
    end
    fclose(f);
    fprintf('\n');
end


function testPrefix = genTestPrefix(T)
testPrefix = sprintf('%u-%u-%u-%u-%s-%u-%u-%u-%s', ...
    T.numF, ...
    T.preload, ...
    T.depth, ...
    T.fold, ...
    T.Ftype, ...
    T.numS, ...
    T.numT, ...
    T.numGPU, ...
    T.weightType);


function testStr = genTestString(T,dropCache)
dc='';
if exist('dropCache') && dropCache
    dc='sudo DROP_CACHE=1 ';
end

testStr = sprintf('%s./Tea %u %u %u %u %s %u %u 0 %u %s %s/ %s 0 %s "%s"', ...
    dc, ...
    T.numF, ...
    T.preload, ...
    T.depth, ...
    T.fold, ...
    T.Ftype, ...
    T.numS, ...
    T.numT, ...
    T.numGPU - 1, ...
    T.weightType, ...
    T.baseDir, ...
    [genTestPrefix(T) T.prefix], ...
    T.log, ...
    T.comment);

