function genTest_Depths()

testStr = 'T6';

default=struct('numF',200,'preload',20,'depth',10,'fold',10,'Ftype','F_CHAR','numS',10*1e6,'numT',50,'numGPU',1,'weightType','W_ONES','baseDir','','prefix','','log','LOG2','comment','');

%Speed:
%T6: Need to test depth of trees: 10 - 23  (All machines, as deep as they can go because we can time each layer) = (5 or 10 tests)
testDir='200-100-7-char';
machines= { ...
    'k5000m',  ['/media/gipadmin/data/' testDir],  ...
    'k80',     ['/home/aaron/forks/tea/data/'    testDir],  ...
    'titanz',  ['/home/gipuser/forks/tea/data/'  testDir],  ...
    'gtx1080', ['/home/aaron/forks/tea/data/'    testDir],  ...
    'gtx580',  ['/home/admin/forks/tea/data/'    testDir],  ...
    };

T=default;
%% Constant test component
% --------------------------------
T.depth=22;
T.fold =22;
T.numS=100*1e6;
T.numT=10;
T.comment='Test: Timing different depths';
% --------------------------------
for i = 2:2:length(machines)
    machine = machines{i-1};
    baseDir = machines{i};
    T.prefix=['-' machine '-' testStr];
    T.baseDir=baseDir;
    f=fopen(sprintf('%s-%s.test',machine,testStr),'w');
    fprintf('%s\n',T.comment);
    fprintf('Machine: %s\n',machine);
    fprintf('%s\n',genTestString(T));
    fprintf(f,'%s\n',genTestString(T));
    fprintf('\n');
    fclose(f);
end


function testPrefix = genTestPrefix(T)
testPrefix = sprintf('%u-%u-%u-%u-%s-%u-%u-%u-%s', ...
    T.numF, ...
    T.preload, ...
    T.depth, ...
    T.fold, ...
    T.Ftype, ...
    T.numS, ...
    T.numT, ...
    T.numGPU, ...
    T.weightType);


function testStr = genTestString(T,dropCache)
dc='';
if exist('dropCache') && dropCache
    dc='sudo DROP_CACHE=1 ';
end

testStr = sprintf('%s./Tea %u %u %u %u %s %u %u 0 %u %s %s %s 0 %s "%s"', ...
    dc, ...
    T.numF, ...
    T.preload, ...
    T.depth, ...
    T.fold, ...
    T.Ftype, ...
    T.numS, ...
    T.numT, ...
    T.numGPU - 1, ...
    T.weightType, ...
    T.baseDir, ...
    [genTestPrefix(T) T.prefix], ...
    T.log, ...
    T.comment);


